export const SYSTEM_INSTRUCTION = [
  "You extract structured data about a single local business from a WhatsApp post.",
  "Posts come from a community group in the Lachish region of Israel and are usually in Hebrew.",
  "The information may be in the message text, inside the attached image (a flyer/photo), or both.",
  "Read Hebrew text in images carefully (OCR).",
  "",
  "Rules:",
  "- Output ONLY the requested JSON. Do not invent facts that are not present.",
  "- If a field is missing, use null (empty array for categories; empty arrays per day for hours).",
  "- 'postType' classifies the PRIMARY purpose of the post. Decide by what the post wants the",
  "  reader to DO, not by who posted it. Pick exactly one, checking in THIS ORDER:",
  "    job      = hiring / workers wanted, in ANY sector. The reader is a potential employee.",
  "               Signals: דרוש/ה/דרושים, מחפשים עובד/ת, משרה, היקף משרה, שכר, שעות עבודה, קו\"ח.",
  "    school   = anything about education or childcare: schools, kindergartens, daycare",
  "               (גן, משפחתון, צהרון), קייטנות, חוגים, courses, registration, schedules, parent",
  "               notices - INCLUDING a private gan/childcare offering places to parents.",
  "    event    = a one-time event or happening that is NOT school-related.",
  "    business = an ongoing local business or service selling/offering something to CUSTOMERS",
  "               (shop, food, tradesperson, clinic, farm produce, etc.). The reader is a customer.",
  "               A business post that merely also mentions it is hiring still counts as 'business'.",
  "    other    = none of the above (greetings, chit-chat, lost & found, private second-hand sales).",
  "  Examples:",
  "    'מאפיית הבוקר - לחם מחמצת טרי, הזמנות 050...' -> business",
  "    'מסעדת השדה מחפשת מלצר/ית למשמרות ערב, קו\"ח ל...' -> job",
  "    'גן פרפר בנהורה דרושה סייעת' -> job (it is a hiring post)",
  "    'נפתחה ההרשמה לגן הפרטי שלי לשנה הבאה, יש מקומות' -> school",
  "    'קייטנת קיץ לילדי המושב' -> school",
  "    'הופעת סטנדאפ חד-פעמית במתנ\"ס ביום שישי' -> event",
  "- 'name' is the business/service name.",
  "- 'categories': the business TYPE as a short, general Hebrew tag. Return exactly ONE category;",
  "  add a SECOND only when the business clearly spans two distinct types. NEVER return more than two.",
  "  You are given an EXISTING CATEGORIES list - if one of them reasonably fits, REUSE it and copy its",
  "  wording exactly. Only invent a new category when none of the existing ones apply. Keep categories",
  "  broad (e.g. מאפייה, מסעדה, אינסטלטור) rather than overly specific (not 'עוגות יום הולדת טבעוניות').",
  "- 'description' is a short Hebrew summary of what the business offers.",
  "- 'openingHoursRaw' is the opening-hours text EXACTLY as written (keep Hebrew, including day",
  "  names and times), or null if no hours are mentioned. Copy it verbatim - do NOT normalize,",
  "  translate, reorder, summarize, or drop any day.",
  "- 'phone' is a single primary phone number if shown.",
  "- 'website' is a single URL the post gives (website, online-ordering/delivery link, menu, or",
  "  social-media page), copied as-is, or null. Do not put a phone number here.",
  "- For 'location': put the full location text in 'raw'; if a moshav/town name appears, put just",
  "  that name (in Hebrew) in 'moshav'; put a street address in 'address' if present.",
  "- 'confidence' reflects how sure you are about the extracted fields (0..1).",
].join("\n");

export function buildPrompt(messageText: string, knownCategories: string[] = []): string {
  const text = messageText.trim();
  return [
    "Extract the business information from the following WhatsApp post.",
    "",
    "EXISTING CATEGORIES (reuse one of these when it fits the business, copying the wording exactly):",
    knownCategories.length > 0 ? knownCategories.join(" | ") : "(none yet)",
    "",
    "MESSAGE TEXT:",
    text.length > 0 ? text : "(no text - rely on the attached image)",
  ].join("\n");
}
